title: Blog
description: "Dr. J - his working blog"
author:
  name: "Jong-Hyouk Lee"
  email: "jonghyouk@sejong.ac.kr"
  url: "https://jonghyouk.github.io/blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "jonghyouk"
year : "2020"
